version: '3.8'
services:
  dev:
    container_name: ridemio_website
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  # prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: prod
  #   ports:
  #     - "4000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   command: npm start